USE [master]
GO
/****** Object:  Database [TechCheckDB]    Script Date: 13.03.2026 03:56:15 ******/
CREATE DATABASE [TechCheckDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TechCheckDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TechCheckDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TechCheckDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TechCheckDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TechCheckDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TechCheckDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TechCheckDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TechCheckDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TechCheckDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TechCheckDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TechCheckDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TechCheckDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [TechCheckDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TechCheckDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TechCheckDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TechCheckDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TechCheckDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TechCheckDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TechCheckDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TechCheckDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TechCheckDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TechCheckDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TechCheckDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TechCheckDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TechCheckDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TechCheckDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TechCheckDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TechCheckDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TechCheckDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TechCheckDB] SET  MULTI_USER 
GO
ALTER DATABASE [TechCheckDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TechCheckDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TechCheckDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TechCheckDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TechCheckDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TechCheckDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TechCheckDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TechCheckDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TechCheckDB]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 13.03.2026 03:56:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Phone] [nvarchar](20) NULL,
	[Email] [nvarchar](100) NULL,
	[Address] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Devices]    Script Date: 13.03.2026 03:56:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Devices](
	[DeviceID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerID] [int] NULL,
	[Brand] [nvarchar](50) NULL,
	[Model] [nvarchar](50) NULL,
	[SerialNumber] [nvarchar](50) NULL,
	[PurchaseDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[DeviceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SerialNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ServiceRecords]    Script Date: 13.03.2026 03:56:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ServiceRecords](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[DeviceID] [int] NULL,
	[TechnicianID] [int] NULL,
	[FailureDescription] [nvarchar](max) NULL,
	[RepairDetails] [nvarchar](max) NULL,
	[Status] [nvarchar](50) NULL,
	[EntryDate] [datetime] NULL,
	[ExitDate] [datetime] NULL,
	[IsChronic] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 13.03.2026 03:56:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[UserRole] [nvarchar](20) NOT NULL,
	[Role] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ServiceRecords] ADD  DEFAULT ('Beklemede') FOR [Status]
GO
ALTER TABLE [dbo].[ServiceRecords] ADD  DEFAULT (getdate()) FOR [EntryDate]
GO
ALTER TABLE [dbo].[ServiceRecords] ADD  DEFAULT ((0)) FOR [IsChronic]
GO
ALTER TABLE [dbo].[Devices]  WITH CHECK ADD FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([CustomerID])
GO
ALTER TABLE [dbo].[ServiceRecords]  WITH CHECK ADD FOREIGN KEY([DeviceID])
REFERENCES [dbo].[Devices] ([DeviceID])
GO
USE [master]
GO
ALTER DATABASE [TechCheckDB] SET  READ_WRITE 
GO
